### ISSUE TITLE
Cannot create a character

### ISSUE THREAD

**Issue by PMBakerJohnson** [PMBakerJohnson/bench-warmers#4]
On the character screen, I type in a character name and a class name and click submit and get an error that seems to be front end.
![image](https://user-images.githubusercontent.com/20603207/63445510-1866a380-c3fe-11e9-8911-0366cb08ed26.png)

**Comment by lily-ayers** [comment]
The Form had all lowercase while the object had properties in Pascal, fixing this corrected the issue!
